# Generated by Django 4.2.2 on 2023-09-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='probs',
            name='numer',
            field=models.IntegerField(null=True, verbose_name='Номер в протоколе'),
        ),
    ]
